/**
 * `rvforge.json` — the marketplace project file (requirements P4 "Create",
 * ADR-294 §4).
 *
 * `forge.config.json` describes how to *build* an RVF into installers.
 * `rvforge.json` describes how to *list and publish* it: the listing metadata
 * a store renders, the publisher identity a release is signed under, the
 * capability contract an installer shows the user, the runtime requirements,
 * and the license. The split is deliberate — a build is reproducible from the
 * former alone, and nothing in the latter can change a build's output.
 *
 * Neither file ever holds credentials. `publisher.keyFile` is a *path* to a
 * key generated by `rvforge init --keygen`; the key itself stays on disk with
 * owner-only permissions and is read only by `src/keys.ts`.
 */

import { readFile, writeFile } from 'node:fs/promises';

import { ForgeError, ForgeErrorCode } from './errors';
import { canonicalJson, sha256String } from './hash';

export const PROJECT_FILENAME = 'rvforge.json';

/** The fifteen ADR-286 capability classes, in the registry model's spelling. */
export const MANIFEST_CAPABILITY_CLASSES = Object.freeze([
  'audio',
  'clipboard',
  'clock',
  'display',
  'filesystem',
  'gpu',
  'inter-agent-messaging',
  'mcp',
  'memory',
  'model',
  'network',
  'persistent-state',
  'process',
  'randomness',
  'sensor',
] as const);

export type ManifestCapabilityClass = (typeof MANIFEST_CAPABILITY_CLASSES)[number];

/**
 * Capability classes whose *request* forces human review (ADR-294 §8).
 *
 * The ADR lists ten triggers; the ones expressible as a capability class are
 * here, and the rest — unrestricted filesystem, arbitrary network — are
 * detected from the scope instead, by {@link VAGUE_SCOPES}.
 */
export const REVIEW_TRIGGER_CLASSES: readonly ManifestCapabilityClass[] = Object.freeze([
  'inter-agent-messaging',
  'process',
  'sensor',
] as const);

/**
 * Scopes too broad to render as a concrete sentence in the install UX.
 *
 * Requirements P6 bans "access your computer"-style copy, which means the
 * *scope* has to be specific enough to write a concrete sentence from. A scope
 * on this list cannot be, so it sets a manual-review trigger rather than
 * shipping as vague prose.
 */
export const VAGUE_SCOPES: readonly string[] = Object.freeze([
  '*',
  'all',
  'all-files',
  'all-folders',
  'any',
  'any-host',
  'arbitrary',
  'full',
  'full-access',
  'unrestricted',
]);

export interface CapabilityRequest {
  class: ManifestCapabilityClass;
  scope: string;
  rationale: string;
}

export interface ProjectListing {
  /** Package name within the publisher's namespace, e.g. `analyst`. */
  name: string;
  displayName: string;
  description: string;
  category: string;
  icon: string | null;
  screenshots: string[];
  priceModel: 'free' | 'open-source' | 'one-time' | 'subscription' | 'usage-based';
}

export interface ProjectPublisher {
  displayName: string;
  identityEvidence: { method: 'dns' | 'github' | 'manual-review'; reference: string };
  contact: { support: string; privacyPolicy: string };
  /** Path to the Ed25519 key file. Never the key itself. */
  keyFile: string | null;
}

export interface ProjectRuntimeRequirements {
  profiles: string[];
  systems: string[];
  /** Declared working-set ceiling in MiB. Required by `pack`. */
  memoryMiB: number | null;
  rvmVersionMin: string;
  stateSchemaVersion: number;
  witnessSchemaVersion: number;
}

export interface RvforgeProject {
  schemaVersion: 1;
  version: string;
  license: string | null;
  listing: ProjectListing;
  publisher: ProjectPublisher;
  runtimeRequirements: ProjectRuntimeRequirements;
  capabilities: {
    defaultPolicy: 'deny';
    requests: CapabilityRequest[];
    denials: ManifestCapabilityClass[];
  };
  modelManifest: { location: 'embedded' | 'publisher-inference' | 'meta-llm' | 'byo'; digests: string[] };
  externalServices: string[];
  state: { checkpointing: boolean; recovery: boolean; rollbackSafeUntilStateSchema: number };
}

/**
 * Default denials: every class the scaffold does not request.
 *
 * Default-deny is already the policy, so the list is redundant to the runtime
 * — but it is what the install UX renders as "this agent cannot", and a user
 * reading a concrete negative list is the point of requirements P6.
 */
export function defaultDenials(requests: readonly CapabilityRequest[]): ManifestCapabilityClass[] {
  const requested = new Set(requests.map((r) => r.class));
  return MANIFEST_CAPABILITY_CLASSES.filter((cls) => !requested.has(cls));
}

/** A ready-to-edit project file with a default-deny capability contract. */
export function defaultProject(overrides: Partial<RvforgeProject> = {}): RvforgeProject {
  const requests: CapabilityRequest[] = overrides.capabilities?.requests ?? [
    { class: 'filesystem', scope: 'user-selected', rationale: 'reads only the documents you choose' },
    { class: 'memory', scope: '512MiB', rationale: 'model working set' },
    { class: 'persistent-state', scope: 'encrypted-local', rationale: 'agent memory between sessions' },
  ];
  return {
    schemaVersion: 1,
    version: overrides.version ?? '0.1.0',
    // `??` would resurrect the default from an explicit null, and an explicit
    // null is exactly what "this listing declares no license" looks like —
    // the condition `pack` has to be able to refuse.
    license: 'license' in overrides ? (overrides.license ?? null) : 'MIT',
    listing: {
      name: 'my-agent',
      displayName: 'My Agent',
      description: 'An RVF agent published with RVForge.',
      category: 'developer-tools',
      icon: null,
      screenshots: [],
      priceModel: 'free',
      ...overrides.listing,
    },
    publisher: {
      displayName: 'Example Publisher',
      identityEvidence: { method: 'manual-review', reference: '' },
      contact: { support: '', privacyPolicy: '' },
      keyFile: null,
      ...overrides.publisher,
    },
    runtimeRequirements: {
      profiles: ['wasm'],
      systems: ['linux-x64', 'macos-universal', 'windows-x64'],
      memoryMiB: 512,
      rvmVersionMin: '0.1.0',
      stateSchemaVersion: 1,
      witnessSchemaVersion: 1,
      ...overrides.runtimeRequirements,
    },
    capabilities: {
      defaultPolicy: 'deny',
      requests,
      denials: overrides.capabilities?.denials ?? defaultDenials(requests),
    },
    modelManifest: { location: 'embedded', digests: [], ...overrides.modelManifest },
    externalServices: overrides.externalServices ?? [],
    state: {
      checkpointing: true,
      recovery: true,
      rollbackSafeUntilStateSchema: 2,
      ...overrides.state,
    },
  };
}

/**
 * The publisher's stable identity: `sha256:` over the canonical JSON of its
 * display name and identity evidence.
 *
 * Deriving it from the identity rather than from a key is what lets a key be
 * rotated without the publisher becoming a different publisher — and what lets
 * `publish` reject a release signed by a key that identity has never
 * registered.
 *
 * This is **not** the `publisherId` a release names. That is the content
 * address of the `PublisherRecord`, per the model's identity rule, and it
 * changes with the record's key set. This value is the key the record's
 * pointer file is filed under, which is how `publish` finds the record again
 * after a rotation.
 */
export const publisherIdFor = (publisher: ProjectPublisher): string =>
  `sha256:${sha256String(
    canonicalJson({
      displayName: publisher.displayName.trim(),
      identityEvidence: {
        method: publisher.identityEvidence.method,
        reference: publisher.identityEvidence.reference.trim(),
      },
    }),
  )}`;

/** Read and validate `rvforge.json`. */
export async function loadProject(path: string): Promise<RvforgeProject> {
  let raw: string;
  try {
    raw = await readFile(path, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      throw new ForgeError(
        ForgeErrorCode.NOT_FOUND,
        `No ${PROJECT_FILENAME} at ${path}. Run "rvforge init" first.`,
        { path },
      );
    }
    throw new ForgeError(ForgeErrorCode.IO, `Cannot read ${path}.`, { path });
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new ForgeError(ForgeErrorCode.CONFIG, `${path} is not valid JSON: ${(err as Error).message}`, {
      path,
    });
  }
  return validateProject(parsed, path);
}

/** Validate an already-parsed project object, filling in defaults. */
export function validateProject(value: unknown, path = PROJECT_FILENAME): RvforgeProject {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new ForgeError(ForgeErrorCode.CONFIG, `${path} must contain a JSON object.`, { path });
  }
  const raw = value as Partial<RvforgeProject>;

  requireText(raw.listing?.name, `${path}: listing.name`);
  requireText(raw.listing?.displayName, `${path}: listing.displayName`);
  requireText(raw.listing?.description, `${path}: listing.description`);
  requireText(raw.listing?.category, `${path}: listing.category`);
  requireText(raw.publisher?.displayName, `${path}: publisher.displayName`);
  requireText(raw.version, `${path}: version`);

  if (raw.capabilities && raw.capabilities.defaultPolicy !== 'deny') {
    throw new ForgeError(
      ForgeErrorCode.POLICY,
      `${path} sets capabilities.defaultPolicy to "${String(raw.capabilities.defaultPolicy)}". ` +
        'The only policy RVForge can express is "deny"; grants are per-request.',
      { path, defaultPolicy: String(raw.capabilities.defaultPolicy) },
    );
  }
  for (const request of raw.capabilities?.requests ?? []) {
    assertKnownClass(request?.class, path, 'capabilities.requests[].class');
    requireText(request?.scope, `${path}: capabilities.requests[].scope`);
    requireText(request?.rationale, `${path}: capabilities.requests[].rationale`);
  }
  for (const denial of raw.capabilities?.denials ?? []) {
    assertKnownClass(denial, path, 'capabilities.denials[]');
  }

  const merged = defaultProject(raw);
  // `defaultProject` merges shallowly per section, which is what a partial
  // override needs — but a caller that supplied `capabilities` gets exactly
  // what they supplied, defaults included for the fields they omitted.
  return {
    ...merged,
    license: raw.license === undefined ? merged.license : raw.license,
    capabilities: {
      defaultPolicy: 'deny',
      requests: raw.capabilities?.requests ?? merged.capabilities.requests,
      denials: raw.capabilities?.denials ?? merged.capabilities.denials,
    },
  };
}

function assertKnownClass(value: unknown, path: string, field: string): void {
  if (!(MANIFEST_CAPABILITY_CLASSES as readonly unknown[]).includes(value)) {
    throw new ForgeError(
      ForgeErrorCode.POLICY,
      `${path}: ${field} is "${String(value)}", which is not one of the fifteen ADR-286 capability classes.`,
      { path, field, value: String(value), known: [...MANIFEST_CAPABILITY_CLASSES] },
    );
  }
}

function requireText(value: unknown, field: string): void {
  if (typeof value !== 'string' || value.trim() === '') {
    throw new ForgeError(ForgeErrorCode.CONFIG, `${field} is required and must be a non-empty string.`, {
      field,
    });
  }
}

export interface ProjectInitResult {
  path: string;
  created: boolean;
  project: RvforgeProject;
}

/** Write a starter `rvforge.json`. */
export async function writeProject(
  path: string,
  project: RvforgeProject,
  options: { force?: boolean } = {},
): Promise<ProjectInitResult> {
  try {
    await writeFile(path, `${JSON.stringify(project, null, 2)}\n`, {
      encoding: 'utf8',
      flag: options.force ? 'w' : 'wx',
    });
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'EEXIST') {
      throw new ForgeError(ForgeErrorCode.CONFIG, `${path} already exists. Pass --force to overwrite it.`, {
        path,
      });
    }
    throw new ForgeError(ForgeErrorCode.IO, `Cannot write ${path}.`, { path });
  }
  return { path, created: true, project };
}
