UPSTREAM_COMMIT: str
UPSTREAM_VERSION: str

class RuVectorError(Exception): ...
class InvalidVectorError(RuVectorError): ...
class DimensionError(InvalidVectorError): ...
class DuplicateIDError(RuVectorError): ...
class StorageError(RuVectorError): ...
class IndexError(RuVectorError): ...
class ClosedError(RuVectorError): ...

class NativeDB:
    def __init__(self, config: str) -> None: ...
    def execute(self, operation: str, args: str) -> str: ...
