# Read only literal exporter metadata, never infer sizes from C expressions.
# Legacy frozen headers lack class metadata and keep the generic class bound.
function(rd_model_capacity header dims_out classes_out)
    file(STRINGS "${header}" lines REGEX "^[ \t]*#[ \t]*define[ \t]+RD_MODEL_(DIMS|CLASSES)([ \t]|$)")
    set(dims "")
    set(classes "")
    foreach(line IN LISTS lines)
        if(NOT line MATCHES "^[ \t]*#[ \t]*define[ \t]+RD_MODEL_(DIMS|CLASSES)[ \t]+([1-9][0-9]*)[ \t]*$")
            message(FATAL_ERROR "Invalid model capacity metadata: ${line}")
        endif()
        set(kind "${CMAKE_MATCH_1}")
        set(value "${CMAKE_MATCH_2}")
        if(kind STREQUAL "DIMS")
            if(NOT dims STREQUAL "" OR value GREATER 768)
                message(FATAL_ERROR "Duplicate or unsupported RD_MODEL_DIMS")
            endif()
            set(dims "${value}")
        else()
            if(NOT classes STREQUAL "" OR value GREATER 16)
                message(FATAL_ERROR "Duplicate or unsupported RD_MODEL_CLASSES")
            endif()
            set(classes "${value}")
        endif()
    endforeach()
    if(dims STREQUAL "")
        message(FATAL_ERROR "Missing RD_MODEL_DIMS")
    endif()
    if(classes STREQUAL "")
        set(classes 16)
    endif()
    set(${dims_out} "${dims}" PARENT_SCOPE)
    set(${classes_out} "${classes}" PARENT_SCOPE)
endfunction()
