// Node-friendly entry for the wasm-bindgen output (regression guard for #323).
//
// Background: the autogenerated `ruvector_onnx_embeddings_wasm.js` is the
// `--target bundler` output, whose first line is
//   import * as wasm from "./ruvector_onnx_embeddings_wasm_bg.wasm";
// Node 22 LTS rejects static `.wasm` imports without
// `--experimental-wasm-modules`, throwing `Unknown file extension ".wasm"`.
// This file replaces that load path with `fs.readFileSync` +
// `WebAssembly.instantiate`, which works on Node 18+ unchanged.
//
// The bundler-target file is left alone so browser/webpack/vite consumers
// keep working with their existing toolchains.

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import * as bg from './ruvector_onnx_embeddings_wasm_bg.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const wasmPath = join(__dirname, 'ruvector_onnx_embeddings_wasm_bg.wasm');

const bytes = readFileSync(wasmPath);
const compiled = await WebAssembly.compile(bytes);

// wasm-bindgen labels the host-import module by the bg.js path; keep this
// key in sync if the binary is ever regenerated with a different name.
const instance = await WebAssembly.instantiate(compiled, {
  './ruvector_onnx_embeddings_wasm_bg.js': bg,
});

bg.__wbg_set_wasm(instance.exports);
if (typeof instance.exports.__wbindgen_start === 'function') {
  instance.exports.__wbindgen_start();
}

export * from './ruvector_onnx_embeddings_wasm_bg.js';
